version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  deploy:
    docker:
      - image: circleci/python:3.9

      # Install Heroku CLI
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh

      # Heroku login
      - run:
          name: Heroku Login
          command: heroku login -i
          environment:
            HEROKU_API_KEY: $HEROKU_API_KEY

      # Other deployment steps go here
      # ...

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main  # Adjust this based on your main branch name
