version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      # Run tests (if applicable)
      # - run:
      #     name: Run Tests
      #     command: python manage.py test

  deploy:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      # Install Heroku CLI
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh

      # Login to Heroku with API Key
      - run:
          name: Heroku Login
          command: heroku login -i
          environment:
            HEROKU_API_KEY: $HEROKU_API_KEY

      # Set Heroku remote URL
      - run:
          name: Set Heroku Git Remote
          command: git remote add heroku https://git.heroku.com/vellyprofessionals.git

      # Build and Deploy to Heroku
      - run:
          name: Deploy to Heroku
          command: |
            python manage.py collectstatic --noinput
            python manage.py migrate --noinput
            git push heroku main

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main  # Adjust this based on your main branch name
